CREATE TABLE DEPARTMENT
(
  ID bigint PRIMARY KEY AUTO_INCREMENT,
  IS_DELETED BOOLEAN DEFAULT FALSE NOT NULL,
  NAME varchar(255)
);
CREATE TABLE EMPLOYEE
(
  ID bigint PRIMARY KEY AUTO_INCREMENT,
  IS_DELETED BOOLEAN DEFAULT FALSE NOT NULL,
  NAME varchar(255),
  DEPARTMENT_ID bigint,
  CONSTRAINT FKBEJTWVG9BXUS2MFFSM3SWJ3U9 FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (ID)
);
CREATE TABLE PROJECT
(
  ID bigint PRIMARY KEY AUTO_INCREMENT,
  IS_DELETED BOOLEAN DEFAULT FALSE,
  NAME varchar(255)
);
CREATE TABLE DEPARTMENT_EMPLOYEE
(
  ID bigint PRIMARY KEY AUTO_INCREMENT,
  DEPARTMENT_ID bigint NOT NULL,
  EMPLOYEE_ID bigint NOT NULL,
  IS_DELETED BOOLEAN DEFAULT FALSE,
  CONSTRAINT FKS2AI09FN82COGWKJ70FMEO34F FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (ID),
  CONSTRAINT FKDLNABUCRLBNWEI5ARHQBSMFFP FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (ID)
);
CREATE TABLE EMP_PROJ
(
  ID bigint PRIMARY KEY AUTO_INCREMENT,
  PROJ_ID bigint NOT NULL,
  EMP_ID bigint NOT NULL,
  IS_DELETED BOOLEAN DEFAULT FALSE,
  CONSTRAINT FKJ350N5WR8YYESIT27CW0AGPJQ FOREIGN KEY (PROJ_ID) REFERENCES PROJECT (ID),
  CONSTRAINT FK10TF71I5H7OS8KDRPM2K97GN2 FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (ID)
);